# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pythonTtest\TDXPystock\login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 270)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(340, 270))
        Dialog.setMaximumSize(QtCore.QSize(340, 270))
        Dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 7, 23);\n"
"background-color: rgb(0, 0, 39);\n"
"gridline-color: rgb(85, 85, 127);\n"
"selection-color: rgb(255, 107, 39);\n"
"selection-background-color: rgb(225, 219, 255);")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setMouseTracking(True)
        self.password.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 2)
        self.loginclearButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginclearButton.setFont(font)
        self.loginclearButton.setObjectName("loginclearButton")
        self.gridLayout.addWidget(self.loginclearButton, 2, 1, 1, 1)
        self.loginsubmitButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginsubmitButton.setFont(font)
        self.loginsubmitButton.setStyleSheet("")
        self.loginsubmitButton.setObjectName("loginsubmitButton")
        self.gridLayout.addWidget(self.loginsubmitButton, 2, 2, 1, 1)
        self.username = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setInputMask("")
        self.username.setText("")
        self.username.setMaxLength(20)
        self.username.setCursorPosition(0)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 1, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 220, 301, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.user_register = QtWidgets.QPushButton(self.layoutWidget1)
        self.user_register.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.user_register.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.user_register.setFont(font)
        self.user_register.setObjectName("user_register")
        self.horizontalLayout.addWidget(self.user_register)
        self.userloginwaringlabel = QtWidgets.QLabel(Dialog)
        self.userloginwaringlabel.setGeometry(QtCore.QRect(51, 190, 201, 20))
        self.userloginwaringlabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"新宋体\";")
        self.userloginwaringlabel.setText("")
        self.userloginwaringlabel.setObjectName("userloginwaringlabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "登录"))
        self.label.setText(_translate("Dialog", "用户名："))
        self.label_2.setText(_translate("Dialog", "密码："))
        self.loginclearButton.setText(_translate("Dialog", "清除"))
        self.loginsubmitButton.setText(_translate("Dialog", "登录"))
        self.label_3.setText(_translate("Dialog", "第一次使用请点击注册"))
        self.user_register.setText(_translate("Dialog", "注册"))
